version: '3'
services:
  tendermint:
    image: tendermint/tendermint:v0.31.3
    volumes:
    - ./tendermint:/tendermint
    user: "1000:1000"
    ports:
      - 0.0.0.0:26656:26656
      - 0.0.0.0:26657:26657

